apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-guestbook-backend
  labels:
    app: java-guestbook
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-guestbook
      tier: backend
  template:
    metadata:
      labels:
        app: java-guestbook
        tier: backend
    spec:
      containers:
      - name: backend
        image: java-guestbook-backend
        ports:
        - name: http-server
          containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        # This environment variable enables debugging support for the container.
        # Remove this to disable the debug build.
        - name: JAVA_TOOL_OPTIONS
          value: -agentlib:jdwp=transport=dt_socket,server=y,address=5005,suspend=n,quiet=y
