version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    commit-message:
      prefix: "chore(deps): "
    rebase-strategy: "disabled"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"] # Security updates are unaffected by this setting
      - dependency-name: "com.google.code.gson:gson" # Dependency is used to illustrate a vulnerability

  - package-ecosystem: "docker"
    directory: "/"
    commit-message:
      prefix: "chore(deps): "
    rebase-strategy: "disabled"
    schedule:
      interval: "monthly"