steps:
  - id: "Build and Push Container Frontend and Backend Images"
    name: 'gcr.io/k8s-skaffold/skaffold'
    entrypoint: /bin/bash
    args:
    - "-xe"
    - "-c"
    - |
      skaffold build --file-output=./artifacts.json \
        --default-repo=${_REGION}-docker.pkg.dev/${PROJECT_ID}/containers \
        --tag=${SHORT_SHA} \
        --profile=dockerfile \
        --push=true
  
  # - id: "Build and Push Container Image: Frontend"
  #   name: "gcr.io/cloud-builders/docker"
  #   entrypoint: "/bin/bash"
  #   dir: "frontend"
  #   args:
  #     - "-c"
  #     - |
  #       docker build -t $_FRONTEND_IMAGE .
  #       docker push $_FRONTEND_IMAGE

  # - id: "Build and Push Container Image: Backend"
  #   name: "gcr.io/cloud-builders/docker"
  #   entrypoint: "/bin/bash"
  #   dir: "backend"
  #   args:
  #     - "-c"
  #     - |
  #       docker build -t $_BACKEND_IMAGE .
  #       docker push $_BACKEND_IMAGE

  - id: "Deploy to Cloud Run"
    name: "gcr.io/cloud-builders/gcloud:latest"
    entrypoint: /bin/bash
    args:
      - "-c"
      - |
        gcloud deploy releases create backend-release \
          --delivery-pipeline=cloudrun-guestbook-app-delivery \
          --skaffold-file=./backend/cloudrun.skaffold.yaml \
          --images=java-guestbook-backend=$BACKEND

        gcloud deploy releases create frontend-release \
          --delivery-pipeline=cloudrun-guestbook-app-delivery \
          --skaffold-file=./frontend/cloudrun.skaffold.yaml \
          --images=java-guestbook-frontend=$FRONTEND


  # - id: "Deploy to Cloud Run"
  #   name: "gcr.io/cloud-builders/gcloud:latest"
  #   entrypoint: /bin/bash
  #   args:
  #     - "-c"
  #     - |
  #       # gcloud run deploy backend \
  #       #   --image us-central1-docker.pkg.dev/${PROJECT_ID}/containers/backend:${SHORT_SHA} \
  #       #   --allow-unauthenticated \
  #       #   --region ${_REGION} 

  #       # echo $(gcloud run services describe backend \
  #       #   --region ${_REGION} \
  #       #   --format='value(status.url)') > _service_url

  #       # gcloud run deploy frontend \
  #       #   --image us-central1-docker.pkg.dev/${PROJECT_ID}/containers/frontend:${SHORT_SHA} \
  #       #   --allow-unauthenticated \
  #       #   --region ${_REGION} \
  #       #   --set-env-vars GUESTBOOK_API_ADDR=$(cat _service_url)

images:
  - $_FRONTEND_IMAGE
  - $_BACKEND_IMAGE

substitutions:
  _FRONTEND_IMAGE: 'us-central1-docker.pkg.dev/${PROJECT_ID}/containers/java-guestbook-frontend:${SHORT_SHA}'
  _BACKEND_IMAGE: 'us-central1-docker.pkg.dev/${PROJECT_ID}/containers/java-guestbook-backend:${SHORT_SHA}'
  _REGION: us-central1
options:
    dynamic_substitutions: true