apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
 name: cloudrun-guestbook-app-delivery
description: main application pipeline
serialPipeline:
 stages:
 - targetId: cloudrun-dev
   profiles: [dev]
 - targetId: cloudrun-prod
   profiles: [prod]
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: cloudrun-dev
description: Cloud Run development service
run:
 location: projects/PROJECT_ID/locations/us-central1
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: cloudrun-prod
description: Cloud Run production service
run:
 location: projects/PROJECT_ID/locations/us-central1