steps:
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "/bin/bash"
    dir: "frontend"
    args:
      - "-c"
      - |
        docker build -t us-central1-docker.pkg.dev/${PROJECT_ID}/containers/frontend:${SHORT_SHA} .
        docker push us-central1-docker.pkg.dev/${PROJECT_ID}/containers/frontend:${SHORT_SHA}

  - id: "Build and Push Container Image"
    name: "gcr.io/cloud-builders/docker"
    entrypoint: "/bin/bash"
    dir: "backend"
    args:
      - "-c"
      - |
        docker build -t us-central1-docker.pkg.dev/${PROJECT_ID}/containers/backend:${SHORT_SHA} .
        docker push us-central1-docker.pkg.dev/${PROJECT_ID}/containers/backend:${SHORT_SHA}

  - id: "Deploy to Cloud Run"
    name: "gcr.io/cloud-builders/gcloud:latest"
    entrypoint: /bin/bash
    args:
      - "-c"
      - |
        gcloud run deploy backend \
          --image us-central1-docker.pkg.dev/${PROJECT_ID}/containers/backend:${SHORT_SHA} \
          --allow-unauthenticated \
          --region ${_REGION} 

        echo $(gcloud run services describe backend \
          --region ${_REGION} \
          --format='value(status.url)') > _service_url

        gcloud run deploy frontend \
          --image us-central1-docker.pkg.dev/${PROJECT_ID}/containers/frontend:${SHORT_SHA} \
          --allow-unauthenticated \
          --region ${_REGION} \
          --set-env-vars GUESTBOOK_API_ADDR=$(cat _service_url)

images:
  - us-central1-docker.pkg.dev/${PROJECT_ID}/containers/frontend:${SHORT_SHA}
  - us-central1-docker.pkg.dev/${PROJECT_ID}/containers/backend:${SHORT_SHA}
substitutions:
  _REGION: us-central1
# gcloud builds submit --config cloudrun.cloudbuild.yaml --substitutions SHORT_SHA=1
